MAX_LIKE_LEVEL = 100
INC_EGO_PROBABILTY_RANDOM = 80
INC_EGO_PROBABILTY_B = 80
INC_INIT = 80
DEC_INIT = 80
DEC_EGO_NOT_ACCEPTED = 70

DEC_EGO_CRONICAL_SINGLE = 0
DEC_EGO_CRONICAL_SINGLE_2 = 25

PATH = "output/"
